[package]
name = "hex_terrain"
version = "0.1.0"
authors = ["Karsten Bock <KarstenBock@gmx.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.3"
euclid = "0.22.1"
terrain = { path = "terrain" }